/*
 * generated by Xtext
 */
package fr.imag.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.imag.ui.internal.UnqlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UnqlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return UnqlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return UnqlActivator.getInstance().getInjector(UnqlActivator.FR_IMAG_UNQL);
	}
	
}
