/*
* generated by Xtext
*/
package fr.imag.ui.contentassist;

import fr.imag.ui.contentassist.AbstractUnqlProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class UnqlProposalProvider extends AbstractUnqlProposalProvider {

}
