/*
* generated by Xtext
*/
package fr.imag.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.imag.services.UnqlGrammarAccess;

public class UnqlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UnqlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.imag.parser.antlr.internal.InternalUnqlParser createParser(XtextTokenStream stream) {
		return new fr.imag.parser.antlr.internal.InternalUnqlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public UnqlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UnqlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
