/*
 * generated by Xtext
 */
package fr.imag;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UnqlRuntimeModule extends fr.imag.AbstractUnqlRuntimeModule {

}
