/*
* generated by Xtext
*/
package fr.imag;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class UnqlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.imag.ui.internal.UnqlActivator.getInstance().getInjector("fr.imag.Unql");
	}
	
}
