/*
 * generated by Xtext
 */
package fr.imag.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UnqlUiModule extends fr.imag.ui.AbstractUnqlUiModule {
	public UnqlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
